name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.m1MChsUG6z8VBMjWXvWbuBBPDnQ+JFsM++EnmYb2 }}
        aws-secret-access-key: ${{ secrets.AKIAW3ZO7GTO5E4HQVZS}}
        aws-region: ${{ secrets.us-east-1 }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: docker build -t myapp:latest .

    - name: Tag Docker Image
      run: |
        docker tag myapp:latest \
        ${{ steps.login-ecr.outputs.registry }}/myapp:latest

    - name: Push to ECR
      run: |
        docker push \
        ${{ steps.login-ecr.outputs.registry }}/myapp:latest

